name: larmap_env
channels:
  - conda-forge
  - bioconda
dependencies:
  - bedtools
  - bowtie2=2.5.3
  - intervaltree
  - numpy
  - pandas
  - python
  - pyfaidx
  - pysam
  - samtools

# M1 mac:
# arch -arm64 brew install bowtie2
# arch -arm64 brew install bedtools
# arch -arm64 brew install samtools