name: larmap_env
channels:
  - conda-forge
  - bioconda
dependencies:
  - bedtools
  - bowtie2
  - intervaltree
  - numpy
  - pandas
  - pyarrow       # pandas whines if this isn't included
  - python
  - pyfaidx
  - pysam
  - samtools
  - star

# M1 mac:
# arch -arm64 brew install bowtie2
# arch -arm64 brew install bedtools
# arch -arm64 brew install samtools