{% set version = "0.11.0" %}

package:
  name: lariatmapper
  version: {{ version }}

source:
  url: https://github.com/fairbrother-lab/LariatMapper/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 3dc6dd618e695d904d5039788966571a57bb8881b5da11aa8963d949ba7b64f5

build:
  number: 0
  noarch: generic
  additional-platforms:
    - osx-arm64
  entry_points:
    - lariatmapper-map: larmap:main
  # run_exports:
  #   - {{ pin_subpackage('lariatmapper', max_pin="x.x") }}
  pin_depends: record

channels:
  - conda-forge
  - bioconda

requirements:
  host:
    - python >=3.9, <=3.11
    - r-base >=4.1         # Explicitly define the r-base version to prevent breakage if something changes in newer versions
    - numpy =2.2.*         # Explicitly define numpy version to address numpy-specific quirks in conda-build
  run:
    - bcftools
    - bedtools
    - bioconductor-biostrings
    - bioconductor-genomicalignments
    - bioconductor-genomicfeatures
    - bioconductor-genomicranges
    - bioconductor-rtracklayer
    - bioconductor-txdbmaker         # Required by GenomicFeatures makeTxDbFromGRanges function
    - bowtie2
    - fsspec
    - hisat2
    - intervaltree
    - pandas
    - pyarrow
    - pyfaidx
    - pysam
    - r-bedtoolsr
    - r-ggplot2
    - r-gt
    - r-magrittr
    - r-optparse
    - r-tidyverse
    - samtools

test:
  files:
    - pyproject.toml
    - build_references.py
    - larmap.py
    - scripts/*
    - tests/*
  requires:
    - pytest
    - pytest-xdist
  commands:
    - echo "dir is $SRC_DIR, Path is $PATH"
    - python3 $SRC_DIR/build_references.py --help
    - python3 $SRC_DIR/larmap.py --help
    # - pytest -n auto $SRC_DIr/tests

about:
  home: https://github.com/fairbrother-lab/LariatMapper
  license: MIT License
  summary: 'LariatMapper: A pipeline for extracting lariats and their branchpoints from RNA-sequencing data.'
  doc_url: https://github.com/fairbrother-lab/LariatMapper
