{% set version = "0.17.0" %}

package:
  name: lariatmapper
  version: {{ version }}

source:
  # You can use the path to the source code on your machine when testing modifications 
  path: /home/mrdawn/Lariat_mapping/LariatMapper
  ## The url below points to the release on GitHub
  # url: https://github.com/fairbrother-lab/LariatMapper/archive/refs/tags/v{{ version }}.tar.gz
  ## Make sure to update the sha256
  # sha256: 

build:
  number: 0
  entry_points:
    - lariatmapper-run = lariatmapper.larmap:main
    - lariatmapper-build = lariatmapper.build_references:main
  noarch: generic       # Bioconductor wants this line
  run_exports:          # Bioconductor also wants these 2 lines
      - {{ pin_subpackage('lariatmapper', max_pin="x.x") }}

channels:
  - conda-forge
  - bioconda

requirements:
  host:
    - git
    - python =3.10.*  # Explicitly define the python version to prevent breakage
    - r-base =4.4.*        # Explicitly define the r-base version to prevent breakage 
    - numpy =2.2.*         # Explicitly define numpy version to address numpy-specific quirks in conda-build
  run:
    - bcftools
    - bedtools
    - bioconductor-biostrings
    - bioconductor-genomicalignments
    - bioconductor-genomicfeatures
    - bioconductor-genomicranges
    - bioconductor-rtracklayer
    - bioconductor-txdbmaker         # Required by GenomicFeatures makeTxDbFromGRanges function
    - bowtie2
    - fsspec
    - hisat2
    - intervaltree
    - pandas
    - pyarrow
    - pyfaidx
    - pysam
    - r-bedtoolsr
    - r-ggplot2
    - r-magrittr
    - r-optparse
    - r-tidyverse
    - samtools

# test:
#   files:
#     - tests/*
#   requires:
#     - pytest
#     - pytest-xdist
#   # Test commands (including pytest) need to be put in run_test.sh
  # to follow bioconda rules (https://bioconda.github.io/contributor/guidelines.html#test-dependencies)

about:
  home: https://github.com/fairbrother-lab/LariatMapper
  license: MIT License
  summary: 'LariatMapper: A pipeline for extracting lariats and their branchpoints from RNA-sequencing data.'
  doc_url: https://github.com/fairbrother-lab/LariatMapper